In [1]:
import optuna
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

import pandas as pd

url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"
columns = ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI',
           'DiabetesPedigreeFunction', 'Age', 'Outcome']

df = pd.read_csv(url, names=columns)

df.head()

c:\Users\kumar\AppData\Local\Programs\Python\Python310\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [2]:
import numpy as np

# Replace zero values with NaN in columns where zero is not a valid value
cols_with_missing_vals = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']
df[cols_with_missing_vals] = df[cols_with_missing_vals].replace(0, np.nan)

# Impute the missing values with the mean of the respective column
df.fillna(df.mean(), inplace=True)

# Check if there are any remaining missing values
print(df.isnull().sum())

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [3]:
# Split into features (X) and target (y)
X = df.drop('Outcome', axis=1)
y = df['Outcome']

# Split data into training and test sets (70% train, 30% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Optimal : Scale the data for better model performance
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

# Check the shape of the data
print(f'Training set shape: {X_train.shape}')
print(f'Test set shape: {X_test.shape}')

Training set shape: (537, 8)
Test set shape: (231, 8)

In [4]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

# Define the objective function
def objective(trial):
  # Suggest values for the hyperparameters
  n_estimators = trial.suggest_int('n_estimators', 50,200)
  max_depth = trial.suggest_int('max_depth', 3, 20)

  # Create the RandomForestClassifier with suggested hyperparameters
  model = RandomForestClassifier(
    n_estimators=n_estimators,
    max_depth=max_depth,
    random_state=42
  )

  # Perform 3-fold cross-validation and calculate accuracy
  score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()
  
  return score  # Return the accuracy score for Optuma to maximize

In [5]:
# Create a study object and optimize the objective function
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.TPESampler())  # we aim to maximize accuracy
study.optimize(objective, n_trials=50) # Run 50 trials to find the best hyperameters

[I 2026-03-22 19:53:37,042] A new study created in memory with name: no-name-20f53c6d-ef44-4254-ab82-f0add383721c
[I 2026-03-22 19:53:37,957] Trial 0 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 117, 'max_depth': 7}. Best is trial 0 with value: 0.7783985102420856.
[I 2026-03-22 19:53:38,465] Trial 1 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 65, 'max_depth': 5}. Best is trial 0 with value: 0.7783985102420856.
[I 2026-03-22 19:53:39,355] Trial 2 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 131, 'max_depth': 11}. Best is trial 0 with value: 0.7783985102420856.
[I 2026-03-22 19:53:40,913] Trial 3 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 188, 'max_depth': 15}. Best is trial 0 with value: 0.7783985102420856.
[I 2026-03-22 19:53:42,145] Trial 4 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 173, 'max_depth': 7}. Best is trial 0 with value: 0.7783985102420856.
[I 2026-03-22 19:53:43,038] Trial 5 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 122, 'max_depth': 7}. Best is trial 0 with value: 0.7783985102420856.
[I 2026-03-22 19:53:43,869] Trial 6 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 100, 'max_depth': 17}. Best is trial 0 with value: 0.7783985102420856.
[I 2026-03-22 19:53:44,482] Trial 7 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 79, 'max_depth': 9}. Best is trial 0 with value: 0.7783985102420856.
[I 2026-03-22 19:53:44,928] Trial 8 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 65, 'max_depth': 10}. Best is trial 0 with value: 0.7783985102420856.
[I 2026-03-22 19:53:45,800] Trial 9 finished with value: 0.756052141527002 and parameters: {'n_estimators': 146, 'max_depth': 3}. Best is trial 0 with value: 0.7783985102420856.
[I 2026-03-22 19:53:46,630] Trial 10 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 102, 'max_depth': 20}. Best is trial 0 with value: 0.7783985102420856.
[I 2026-03-22 19:53:46,975] Trial 11 finished with value: 0.750465549348231 and parameters: {'n_estimators': 63, 'max_depth': 3}. Best is trial 0 with value: 0.7783985102420856.
[I 2026-03-22 19:53:47,308] Trial 12 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 50, 'max_depth': 6}. Best is trial 0 with value: 0.7783985102420856.
[I 2026-03-22 19:53:47,909] Trial 13 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 93, 'max_depth': 5}. Best is trial 0 with value: 0.7783985102420856.
[I 2026-03-22 19:53:48,952] Trial 14 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 158, 'max_depth': 8}. Best is trial 0 with value: 0.7783985102420856.
[I 2026-03-22 19:53:49,822] Trial 15 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 117, 'max_depth': 13}. Best is trial 0 with value: 0.7783985102420856.
[I 2026-03-22 19:53:51,218] Trial 16 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 199, 'max_depth': 5}. Best is trial 0 with value: 0.7783985102420856.
[I 2026-03-22 19:53:51,815] Trial 17 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 81, 'max_depth': 12}. Best is trial 0 with value: 0.7783985102420856.
[I 2026-03-22 19:53:52,920] Trial 18 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 143, 'max_depth': 4}. Best is trial 0 with value: 0.7783985102420856.
[I 2026-03-22 19:53:54,696] Trial 19 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 111, 'max_depth': 9}. Best is trial 0 with value: 0.7783985102420856.
[I 2026-03-22 19:53:56,044] Trial 20 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 83, 'max_depth': 6}. Best is trial 0 with value: 0.7783985102420856.
[I 2026-03-22 19:53:58,321] Trial 21 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 127, 'max_depth': 7}. Best is trial 21 with value: 0.7802607076350093.
[I 2026-03-22 19:54:01,026] Trial 22 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 157, 'max_depth': 8}. Best is trial 21 with value: 0.7802607076350093.
[I 2026-03-22 19:54:03,147] Trial 23 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 133, 'max_depth': 5}. Best is trial 21 with value: 0.7802607076350093.
[I 2026-03-22 19:54:04,998] Trial 24 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 107, 'max_depth': 7}. Best is trial 21 with value: 0.7802607076350093.
[I 2026-03-22 19:54:07,335] Trial 25 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 143, 'max_depth': 10}. Best is trial 21 with value: 0.7802607076350093.
[I 2026-03-22 19:54:09,038] Trial 26 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 91, 'max_depth': 14}. Best is trial 21 with value: 0.7802607076350093.
[I 2026-03-22 19:54:11,837] Trial 27 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 166, 'max_depth': 4}. Best is trial 21 with value: 0.7802607076350093.
[I 2026-03-22 19:54:13,025] Trial 28 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 71, 'max_depth': 8}. Best is trial 21 with value: 0.7802607076350093.
[I 2026-03-22 19:54:15,343] Trial 29 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 134, 'max_depth': 12}. Best is trial 21 with value: 0.7802607076350093.
[I 2026-03-22 19:54:16,081] Trial 30 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 54, 'max_depth': 11}. Best is trial 21 with value: 0.7802607076350093.
[I 2026-03-22 19:54:17,707] Trial 31 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 123, 'max_depth': 6}. Best is trial 21 with value: 0.7802607076350093.
[I 2026-03-22 19:54:19,511] Trial 32 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 123, 'max_depth': 7}. Best is trial 21 with value: 0.7802607076350093.
[I 2026-03-22 19:54:21,323] Trial 33 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 118, 'max_depth': 9}. Best is trial 21 with value: 0.7802607076350093.
[I 2026-03-22 19:54:23,738] Trial 34 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 183, 'max_depth': 4}. Best is trial 21 with value: 0.7802607076350093.
[I 2026-03-22 19:54:25,060] Trial 35 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 94, 'max_depth': 7}. Best is trial 21 with value: 0.7802607076350093.
[I 2026-03-22 19:54:26,872] Trial 36 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 128, 'max_depth': 16}. Best is trial 21 with value: 0.7802607076350093.
[I 2026-03-22 19:54:29,075] Trial 37 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 134, 'max_depth': 16}. Best is trial 21 with value: 0.7802607076350093.
[I 2026-03-22 19:54:31,299] Trial 38 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 152, 'max_depth': 16}. Best is trial 21 with value: 0.7802607076350093.
[I 2026-03-22 19:54:32,897] Trial 39 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 112, 'max_depth': 19}. Best is trial 21 with value: 0.7802607076350093.
[I 2026-03-22 19:54:35,316] Trial 40 finished with value: 0.7765363128491619 and parameters: {'n_estimators': 171, 'max_depth': 17}. Best is trial 21 with value: 0.7802607076350093.
[I 2026-03-22 19:54:37,157] Trial 41 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 131, 'max_depth': 10}. Best is trial 21 with value: 0.7802607076350093.
[I 2026-03-22 19:54:38,500] Trial 42 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 100, 'max_depth': 6}. Best is trial 21 with value: 0.7802607076350093.
[I 2026-03-22 19:54:40,378] Trial 43 finished with value: 0.7560521415270017 and parameters: {'n_estimators': 127, 'max_depth': 3}. Best is trial 21 with value: 0.7802607076350093.
[I 2026-03-22 19:54:42,365] Trial 44 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 142, 'max_depth': 18}. Best is trial 21 with value: 0.7802607076350093.
[I 2026-03-22 19:54:44,083] Trial 45 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 117, 'max_depth': 14}. Best is trial 21 with value: 0.7802607076350093.
[I 2026-03-22 19:54:45,731] Trial 46 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 105, 'max_depth': 8}. Best is trial 21 with value: 0.7802607076350093.
[I 2026-03-22 19:54:46,730] Trial 47 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 73, 'max_depth': 5}. Best is trial 21 with value: 0.7802607076350093.
[I 2026-03-22 19:54:48,854] Trial 48 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 139, 'max_depth': 11}. Best is trial 21 with value: 0.7802607076350093.
[I 2026-03-22 19:54:51,320] Trial 49 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 150, 'max_depth': 20}. Best is trial 21 with value: 0.7802607076350093.

In [6]:
# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7802607076350093
Best hyperparameters: {'n_estimators': 127, 'max_depth': 7}

In [7]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.74

Samplers in Optuna

In [8]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import cross_val_score

# Define the objective function
def objective(trial):
  # Suggest values for the hyperparameters
  n_estimators = trial.suggest_int('n_estimators', 50, 200)
  max_depth = trial.suggest_int('max_depth', 3 , 20)

  # Create the RandomForestClassifier with suggested hyperparameters
  model = RandomForestClassifier(
    n_estimators=n_estimators,
    max_depth=max_depth,
    random_state=42
  )

  # Perform 3-fold cross-validation and calculate accuracy
  score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()

  return score

In [9]:
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.RandomSampler())  # We aim to maximize accuracy
study.optimize(objective, n_trials=50)  # Run 50 trials to find the best hyperparameters

[I 2026-03-22 19:54:52,180] A new study created in memory with name: no-name-3d108cdc-eb8a-48e4-95ca-2776b0b94b0c
[I 2026-03-22 19:54:53,237] Trial 0 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 69, 'max_depth': 17}. Best is trial 0 with value: 0.7765363128491621.
[I 2026-03-22 19:54:55,197] Trial 1 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 122, 'max_depth': 19}. Best is trial 1 with value: 0.7783985102420856.
[I 2026-03-22 19:54:56,854] Trial 2 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 108, 'max_depth': 14}. Best is trial 1 with value: 0.7783985102420856.
[I 2026-03-22 19:54:59,530] Trial 3 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 162, 'max_depth': 13}. Best is trial 1 with value: 0.7783985102420856.
[I 2026-03-22 19:55:00,736] Trial 4 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 69, 'max_depth': 13}. Best is trial 1 with value: 0.7783985102420856.
[I 2026-03-22 19:55:02,077] Trial 5 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 80, 'max_depth': 19}. Best is trial 1 with value: 0.7783985102420856.
[I 2026-03-22 19:55:04,665] Trial 6 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 178, 'max_depth': 8}. Best is trial 1 with value: 0.7783985102420856.
[I 2026-03-22 19:55:05,837] Trial 7 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 94, 'max_depth': 5}. Best is trial 1 with value: 0.7783985102420856.
[I 2026-03-22 19:55:06,725] Trial 8 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 59, 'max_depth': 12}. Best is trial 1 with value: 0.7783985102420856.
[I 2026-03-22 19:55:08,595] Trial 9 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 133, 'max_depth': 16}. Best is trial 9 with value: 0.7802607076350093.
[I 2026-03-22 19:55:10,065] Trial 10 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 98, 'max_depth': 6}. Best is trial 9 with value: 0.7802607076350093.
[I 2026-03-22 19:55:12,468] Trial 11 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 164, 'max_depth': 11}. Best is trial 9 with value: 0.7802607076350093.
[I 2026-03-22 19:55:14,346] Trial 12 finished with value: 0.7746741154562383 and parameters: {'n_estimators': 132, 'max_depth': 19}. Best is trial 9 with value: 0.7802607076350093.
[I 2026-03-22 19:55:16,732] Trial 13 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 197, 'max_depth': 3}. Best is trial 9 with value: 0.7802607076350093.
[I 2026-03-22 19:55:19,040] Trial 14 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 170, 'max_depth': 5}. Best is trial 9 with value: 0.7802607076350093.
[I 2026-03-22 19:55:20,121] Trial 15 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 74, 'max_depth': 12}. Best is trial 9 with value: 0.7802607076350093.
[I 2026-03-22 19:55:21,945] Trial 16 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 177, 'max_depth': 5}. Best is trial 9 with value: 0.7802607076350093.
[I 2026-03-22 19:55:23,940] Trial 17 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 167, 'max_depth': 16}. Best is trial 9 with value: 0.7802607076350093.
[I 2026-03-22 19:55:26,020] Trial 18 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 154, 'max_depth': 4}. Best is trial 9 with value: 0.7802607076350093.
[I 2026-03-22 19:55:27,339] Trial 19 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 98, 'max_depth': 4}. Best is trial 9 with value: 0.7802607076350093.
[I 2026-03-22 19:55:29,593] Trial 20 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 158, 'max_depth': 11}. Best is trial 9 with value: 0.7802607076350093.
[I 2026-03-22 19:55:32,321] Trial 21 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 172, 'max_depth': 20}. Best is trial 9 with value: 0.7802607076350093.
[I 2026-03-22 19:55:34,284] Trial 22 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 129, 'max_depth': 15}. Best is trial 9 with value: 0.7802607076350093.
[I 2026-03-22 19:55:35,267] Trial 23 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 63, 'max_depth': 8}. Best is trial 9 with value: 0.7802607076350093.
[I 2026-03-22 19:55:37,006] Trial 24 finished with value: 0.7560521415270017 and parameters: {'n_estimators': 129, 'max_depth': 3}. Best is trial 9 with value: 0.7802607076350093.
[I 2026-03-22 19:55:39,243] Trial 25 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 144, 'max_depth': 20}. Best is trial 9 with value: 0.7802607076350093.
[I 2026-03-22 19:55:41,867] Trial 26 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 145, 'max_depth': 9}. Best is trial 9 with value: 0.7802607076350093.
[I 2026-03-22 19:55:43,761] Trial 27 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 101, 'max_depth': 8}. Best is trial 9 with value: 0.7802607076350093.
[I 2026-03-22 19:55:45,378] Trial 28 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 84, 'max_depth': 18}. Best is trial 9 with value: 0.7802607076350093.
[I 2026-03-22 19:55:46,787] Trial 29 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 72, 'max_depth': 6}. Best is trial 9 with value: 0.7802607076350093.
[I 2026-03-22 19:55:48,903] Trial 30 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 104, 'max_depth': 15}. Best is trial 9 with value: 0.7802607076350093.
[I 2026-03-22 19:55:50,369] Trial 31 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 77, 'max_depth': 7}. Best is trial 9 with value: 0.7802607076350093.
[I 2026-03-22 19:55:52,210] Trial 32 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 160, 'max_depth': 19}. Best is trial 9 with value: 0.7802607076350093.
[I 2026-03-22 19:55:53,154] Trial 33 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 134, 'max_depth': 5}. Best is trial 9 with value: 0.7802607076350093.
[I 2026-03-22 19:55:53,972] Trial 34 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 91, 'max_depth': 15}. Best is trial 9 with value: 0.7802607076350093.
[I 2026-03-22 19:55:55,814] Trial 35 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 106, 'max_depth': 15}. Best is trial 9 with value: 0.7802607076350093.
[I 2026-03-22 19:55:57,745] Trial 36 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 105, 'max_depth': 10}. Best is trial 9 with value: 0.7802607076350093.
[I 2026-03-22 19:55:58,827] Trial 37 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 56, 'max_depth': 15}. Best is trial 9 with value: 0.7802607076350093.
[I 2026-03-22 19:56:00,583] Trial 38 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 95, 'max_depth': 13}. Best is trial 9 with value: 0.7802607076350093.
[I 2026-03-22 19:56:03,136] Trial 39 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 171, 'max_depth': 5}. Best is trial 9 with value: 0.7802607076350093.
[I 2026-03-22 19:56:05,130] Trial 40 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 153, 'max_depth': 11}. Best is trial 9 with value: 0.7802607076350093.
[I 2026-03-22 19:56:07,264] Trial 41 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 145, 'max_depth': 11}. Best is trial 9 with value: 0.7802607076350093.
[I 2026-03-22 19:56:08,922] Trial 42 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 106, 'max_depth': 10}. Best is trial 9 with value: 0.7802607076350093.
[I 2026-03-22 19:56:10,177] Trial 43 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 80, 'max_depth': 15}. Best is trial 9 with value: 0.7802607076350093.
[I 2026-03-22 19:56:11,027] Trial 44 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 61, 'max_depth': 16}. Best is trial 9 with value: 0.7802607076350093.
[I 2026-03-22 19:56:13,252] Trial 45 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 158, 'max_depth': 20}. Best is trial 9 with value: 0.7802607076350093.
[I 2026-03-22 19:56:14,706] Trial 46 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 101, 'max_depth': 15}. Best is trial 9 with value: 0.7802607076350093.
[I 2026-03-22 19:56:17,170] Trial 47 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 183, 'max_depth': 11}. Best is trial 9 with value: 0.7802607076350093.
[I 2026-03-22 19:56:19,891] Trial 48 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 194, 'max_depth': 16}. Best is trial 9 with value: 0.7802607076350093.
[I 2026-03-22 19:56:21,882] Trial 49 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 149, 'max_depth': 6}. Best is trial 9 with value: 0.7802607076350093.

In [10]:

# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7802607076350093
Best hyperparameters: {'n_estimators': 133, 'max_depth': 16}

In [11]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.74

In [12]:
search_space = {
  'n_estimators': [50, 100, 150, 200],
  'max_depth' : [5,10,15,20]
}

In [13]:
# Create a study and optimize it using GridSampler
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.GridSampler(search_space))
study.optimize(objective)

[I 2026-03-22 19:56:22,880] A new study created in memory with name: no-name-71c6267c-9d51-4688-9fa4-1837678d0955
[I 2026-03-22 19:56:24,301] Trial 0 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 100, 'max_depth': 5}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-03-22 19:56:26,701] Trial 1 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 150, 'max_depth': 10}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-03-22 19:56:27,459] Trial 2 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 50, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-03-22 19:56:29,122] Trial 3 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 100, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-03-22 19:56:30,557] Trial 4 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 100, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-03-22 19:56:31,355] Trial 5 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 50, 'max_depth': 10}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-03-22 19:56:33,365] Trial 6 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 150, 'max_depth': 5}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-03-22 19:56:35,713] Trial 7 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 150, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-03-22 19:56:37,575] Trial 8 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 150, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-03-22 19:56:40,180] Trial 9 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 200, 'max_depth': 10}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-03-22 19:56:42,987] Trial 10 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 200, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-03-22 19:56:45,858] Trial 11 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 200, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-03-22 19:56:48,497] Trial 12 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 200, 'max_depth': 5}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-03-22 19:56:49,151] Trial 13 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 50, 'max_depth': 5}. Best is trial 13 with value: 0.7746741154562384.
[I 2026-03-22 19:56:50,477] Trial 14 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 100, 'max_depth': 10}. Best is trial 13 with value: 0.7746741154562384.
[I 2026-03-22 19:56:51,289] Trial 15 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 50, 'max_depth': 20}. Best is trial 13 with value: 0.7746741154562384.

In [14]:

# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7746741154562384
Best hyperparameters: {'n_estimators': 50, 'max_depth': 5}

In [15]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.74

optuna visualizations

In [16]:
# For visualizations
from optuna.visualization import plot_optimization_history, plot_parallel_coordinate, plot_slice, plot_contour, plot_param_importances

In [17]:
# 1. Optimization History
plot_optimization_history(study).show()

In [18]:
# 2. Parallel Coordinates Plot
plot_parallel_coordinate(study).show()

In [19]:
# 3. Slice Plot
plot_slice(study).show()

In [20]:
# 4. Contour Plot
plot_contour(study).show()

In [21]:
# 5. Hyperparameter Importance
plot_param_importances(study).show()

Optimizing Multiple ML Models

In [22]:
# Importing the required libraries
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC

In [23]:
# Define the objective function for Optuna
def objective(trial):
    # Choose the algorithm to tune
    classifier_name = trial.suggest_categorical('classifier', ['SVM', 'RandomForest', 'GradientBoosting'])

    if classifier_name == 'SVM':
        # SVM hyperparameters
        c = trial.suggest_float('C', 0.1, 100, log=True)
        kernel = trial.suggest_categorical('kernel', ['linear', 'rbf', 'poly', 'sigmoid'])
        gamma = trial.suggest_categorical('gamma', ['scale', 'auto'])

        model = SVC(C=c, kernel=kernel, gamma=gamma, random_state=42)

    elif classifier_name == 'RandomForest':
        # Random Forest hyperparameters
        n_estimators = trial.suggest_int('n_estimators', 50, 300)
        max_depth = trial.suggest_int('max_depth', 3, 20)
        min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
        min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)
        bootstrap = trial.suggest_categorical('bootstrap', [True, False])

        model = RandomForestClassifier(
            n_estimators=n_estimators,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            bootstrap=bootstrap,
            random_state=42
        )

    elif classifier_name == 'GradientBoosting':
        # Gradient Boosting hyperparameters
        n_estimators = trial.suggest_int('n_estimators', 50, 300)
        learning_rate = trial.suggest_float('learning_rate', 0.01, 0.3, log=True)
        max_depth = trial.suggest_int('max_depth', 3, 20)
        min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
        min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)

        model = GradientBoostingClassifier(
            n_estimators=n_estimators,
            learning_rate=learning_rate,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            random_state=42
        )

    # Perform cross-validation and return the mean accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()
    return score

In [24]:
# Create a study and optimize it using CmaEsSampler
study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=100)

[I 2026-03-22 20:23:26,634] A new study created in memory with name: no-name-ebcf7b2f-6f8a-42f4-83cc-84941c93f97c
[I 2026-03-22 20:23:27,437] Trial 0 finished with value: 0.7690875232774674 and parameters: {'classifier': 'RandomForest', 'n_estimators': 260, 'max_depth': 20, 'min_samples_split': 8, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-03-22 20:23:27,463] Trial 1 finished with value: 0.696461824953445 and parameters: {'classifier': 'SVM', 'C': 17.990748618948608, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-03-22 20:23:28,047] Trial 2 finished with value: 0.7672253258845437 and parameters: {'classifier': 'RandomForest', 'n_estimators': 191, 'max_depth': 16, 'min_samples_split': 4, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-03-22 20:23:28,704] Trial 3 finished with value: 0.7616387337057727 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 144, 'learning_rate': 0.09794053725327717, 'max_depth': 5, 'min_samples_split': 9, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-03-22 20:23:31,710] Trial 4 finished with value: 0.756052141527002 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 230, 'learning_rate': 0.03205276851685815, 'max_depth': 17, 'min_samples_split': 3, 'min_samples_leaf': 3}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-03-22 20:23:32,344] Trial 5 finished with value: 0.7653631284916201 and parameters: {'classifier': 'RandomForest', 'n_estimators': 207, 'max_depth': 17, 'min_samples_split': 5, 'min_samples_leaf': 6, 'bootstrap': False}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-03-22 20:23:32,870] Trial 6 finished with value: 0.7728119180633147 and parameters: {'classifier': 'RandomForest', 'n_estimators': 185, 'max_depth': 7, 'min_samples_split': 7, 'min_samples_leaf': 7, 'bootstrap': False}. Best is trial 6 with value: 0.7728119180633147.
[I 2026-03-22 20:23:32,884] Trial 7 finished with value: 0.7821229050279329 and parameters: {'classifier': 'SVM', 'C': 0.364420662211767, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 7 with value: 0.7821229050279329.
[I 2026-03-22 20:23:34,070] Trial 8 finished with value: 0.7392923649906891 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 250, 'learning_rate': 0.29729732222830285, 'max_depth': 17, 'min_samples_split': 3, 'min_samples_leaf': 5}. Best is trial 7 with value: 0.7821229050279329.
[I 2026-03-22 20:23:34,092] Trial 9 finished with value: 0.7094972067039106 and parameters: {'classifier': 'SVM', 'C': 11.19513892917707, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 7 with value: 0.7821229050279329.
[I 2026-03-22 20:23:34,114] Trial 10 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1224706211488675, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-22 20:23:34,135] Trial 11 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10963224305326791, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-22 20:23:34,155] Trial 12 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1108744819541546, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-22 20:23:34,176] Trial 13 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.6729124780459543, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-22 20:23:34,219] Trial 14 finished with value: 0.7094972067039107 and parameters: {'classifier': 'SVM', 'C': 0.10302966320419021, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-22 20:23:34,243] Trial 15 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 1.4878485940523543, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-22 20:23:34,261] Trial 16 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.3324799379596852, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-22 20:23:34,280] Trial 17 finished with value: 0.7337057728119181 and parameters: {'classifier': 'SVM', 'C': 3.022323549088142, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-22 20:23:34,295] Trial 18 finished with value: 0.7001862197392924 and parameters: {'classifier': 'SVM', 'C': 81.2986175817404, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-22 20:23:34,830] Trial 19 finished with value: 0.7653631284916201 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 91, 'learning_rate': 0.011898375226799365, 'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 10}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-22 20:23:34,855] Trial 20 finished with value: 0.756052141527002 and parameters: {'classifier': 'SVM', 'C': 0.24595542967300812, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-22 20:23:34,876] Trial 21 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10507056996663044, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-22 20:23:34,897] Trial 22 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10491379762876546, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-22 20:23:34,917] Trial 23 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.6439944370158195, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-22 20:23:34,935] Trial 24 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.21580398638353857, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-22 20:23:34,971] Trial 25 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.8764664360953043, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-22 20:23:34,993] Trial 26 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.2124665693747663, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-22 20:23:35,015] Trial 27 finished with value: 0.7150837988826816 and parameters: {'classifier': 'SVM', 'C': 0.1701841611723683, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-22 20:23:35,181] Trial 28 finished with value: 0.7616387337057727 and parameters: {'classifier': 'RandomForest', 'n_estimators': 57, 'max_depth': 3, 'min_samples_split': 6, 'min_samples_leaf': 10, 'bootstrap': True}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-22 20:23:38,196] Trial 29 finished with value: 0.6983240223463687 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 296, 'learning_rate': 0.010754447381212479, 'max_depth': 12, 'min_samples_split': 2, 'min_samples_leaf': 1}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-22 20:23:38,581] Trial 30 finished with value: 0.7728119180633147 and parameters: {'classifier': 'RandomForest', 'n_estimators': 134, 'max_depth': 13, 'min_samples_split': 10, 'min_samples_leaf': 8, 'bootstrap': False}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-22 20:23:38,596] Trial 31 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.12348153056452753, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-22 20:23:38,615] Trial 32 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10104731765765756, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-22 20:23:38,634] Trial 33 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.3413188134097077, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-22 20:23:38,650] Trial 34 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.18084206834400054, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-22 20:23:38,673] Trial 35 finished with value: 0.7635009310986964 and parameters: {'classifier': 'SVM', 'C': 0.42936691361796475, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-22 20:23:38,698] Trial 36 finished with value: 0.7728119180633147 and parameters: {'classifier': 'SVM', 'C': 0.17141726078968936, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-22 20:23:39,105] Trial 37 finished with value: 0.7597765363128491 and parameters: {'classifier': 'RandomForest', 'n_estimators': 133, 'max_depth': 9, 'min_samples_split': 6, 'min_samples_leaf': 9, 'bootstrap': True}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-22 20:23:39,615] Trial 38 finished with value: 0.7281191806331471 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 56, 'learning_rate': 0.2910146638637154, 'max_depth': 20, 'min_samples_split': 8, 'min_samples_leaf': 6}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-22 20:23:39,635] Trial 39 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 1.0504335034820906, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-22 20:23:40,010] Trial 40 finished with value: 0.7616387337057727 and parameters: {'classifier': 'RandomForest', 'n_estimators': 102, 'max_depth': 14, 'min_samples_split': 2, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-22 20:23:40,026] Trial 41 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10045851744122365, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-22 20:23:40,044] Trial 42 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.15333663656775742, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-22 20:23:40,075] Trial 43 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.15826253664907683, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-22 20:23:40,097] Trial 44 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.2621294648925139, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-22 20:23:40,115] Trial 45 finished with value: 0.690875232774674 and parameters: {'classifier': 'SVM', 'C': 17.031337656030292, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-22 20:23:40,134] Trial 46 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.47455974328403294, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-22 20:23:41,342] Trial 47 finished with value: 0.7560521415270017 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 299, 'learning_rate': 0.06776735703565606, 'max_depth': 3, 'min_samples_split': 5, 'min_samples_leaf': 8}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-22 20:23:41,362] Trial 48 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.16383439825663054, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-22 20:23:41,386] Trial 49 finished with value: 0.7355679702048418 and parameters: {'classifier': 'SVM', 'C': 2.5026943427518753, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-22 20:23:41,415] Trial 50 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.14289511852703426, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-22 20:23:41,448] Trial 51 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.14595214007903878, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-22 20:23:41,510] Trial 52 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 5.277653532866919, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-22 20:23:41,541] Trial 53 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.15397361512722083, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-22 20:23:41,571] Trial 54 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.27821624875385637, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-22 20:23:41,613] Trial 55 finished with value: 0.7523277467411545 and parameters: {'classifier': 'SVM', 'C': 0.1362729511803811, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-22 20:23:41,653] Trial 56 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.4740177766269887, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-22 20:23:43,374] Trial 57 finished with value: 0.7523277467411545 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 158, 'learning_rate': 0.03044605583750249, 'max_depth': 7, 'min_samples_split': 8, 'min_samples_leaf': 5}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-22 20:23:43,393] Trial 58 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.29071714609283045, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-22 20:23:43,418] Trial 59 finished with value: 0.7001862197392924 and parameters: {'classifier': 'SVM', 'C': 73.03026427873107, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-22 20:23:43,843] Trial 60 finished with value: 0.7541899441340782 and parameters: {'classifier': 'RandomForest', 'n_estimators': 98, 'max_depth': 10, 'min_samples_split': 4, 'min_samples_leaf': 7, 'bootstrap': True}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-22 20:23:43,859] Trial 61 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.13849488911725677, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-22 20:23:43,880] Trial 62 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.13860105299620412, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-22 20:23:43,897] Trial 63 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.2021878045611099, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-22 20:23:43,919] Trial 64 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.14489993863510428, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-22 20:23:43,937] Trial 65 finished with value: 0.7188081936685289 and parameters: {'classifier': 'SVM', 'C': 0.22603145558680773, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-22 20:23:43,960] Trial 66 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.13246933947679781, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-22 20:23:43,993] Trial 67 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.34239960829823074, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-22 20:23:44,034] Trial 68 finished with value: 0.7467411545623835 and parameters: {'classifier': 'SVM', 'C': 0.12386641825949038, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-22 20:23:44,056] Trial 69 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.22370803067919745, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-22 20:23:46,916] Trial 70 finished with value: 0.7411545623836128 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 212, 'learning_rate': 0.1291280523285918, 'max_depth': 15, 'min_samples_split': 7, 'min_samples_leaf': 4}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-22 20:23:46,935] Trial 71 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.12979708592146647, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-22 20:23:46,956] Trial 72 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10063730377159621, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-22 20:23:46,979] Trial 73 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.19724881834456828, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-22 20:23:47,007] Trial 74 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.16524095856670892, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-22 20:23:47,039] Trial 75 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.27736530447753205, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-22 20:23:47,770] Trial 76 finished with value: 0.7709497206703911 and parameters: {'classifier': 'RandomForest', 'n_estimators': 264, 'max_depth': 7, 'min_samples_split': 9, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-22 20:23:47,785] Trial 77 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.12579340821351015, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-22 20:23:47,806] Trial 78 finished with value: 0.7821229050279329 and parameters: {'classifier': 'SVM', 'C': 0.3779112279939519, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-22 20:23:47,823] Trial 79 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.18524756473184567, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-22 20:23:47,859] Trial 80 finished with value: 0.7188081936685289 and parameters: {'classifier': 'SVM', 'C': 6.644113371640373, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-22 20:23:47,879] Trial 81 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.13252730357326378, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.

In [25]:
# Retrieve the best trial
best_trial = study.best_trial
print("Best trial parameters:", best_trial.params)
print("Best trial accuracy:", best_trial.value)

Best trial parameters: {'classifier': 'SVM', 'C': 0.1224706211488675, 'kernel': 'linear', 'gamma': 'scale'}
Best trial accuracy: 0.7895716945996275

In [26]:
study.trials_dataframe()

,number,value,datetime_start,datetime_complete,duration,params_C,params_bootstrap,params_classifier,params_gamma,params_kernel,params_learning_rate,params_max_depth,params_min_samples_leaf,params_min_samples_split,params_n_estimators,state
0,0,0.769088,2026-03-22 20:23:26.636866,2026-03-22 20:23:27.437285,0 days 00:00:00.800419,NaN,True,RandomForest,NaN,NaN,NaN,20.0,2.0,8.0,260.0,COMPLETE
1,1,0.696462,2026-03-22 20:23:27.439284,2026-03-22 20:23:27.463377,0 days 00:00:00.024093,17.990749,NaN,SVM,auto,sigmoid,NaN,NaN,NaN,NaN,NaN,COMPLETE
2,2,0.767225,2026-03-22 20:23:27.464377,2026-03-22 20:23:28.047690,0 days 00:00:00.583313,NaN,True,RandomForest,NaN,NaN,NaN,16.0,3.0,4.0,191.0,COMPLETE
3,3,0.761639,2026-03-22 20:23:28.049688,2026-03-22 20:23:28.703742,0 days 00:00:00.654054,NaN,NaN,GradientBoosting,NaN,NaN,0.097941,5.0,4.0,9.0,144.0,COMPLETE
4,4,0.756052,2026-03-22 20:23:28.704748,2026-03-22 20:23:31.710588,0 days 00:00:03.005840,NaN,NaN,GradientBoosting,NaN,NaN,0.032053,17.0,3.0,3.0,230.0,COMPLETE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,0.783985,2026-03-22 20:23:48.983546,2026-03-22 20:23:49.007471,0 days 00:00:00.023925,1.450542,NaN,SVM,auto,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
96,96,0.789572,2026-03-22 20:23:49.008523,2026-03-22 20:23:49.025470,0 days 00:00:00.016947,0.114939,NaN,SVM,scale,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
97,97,0.785847,2026-03-22 20:23:49.026484,2026-03-22 20:23:49.056958,0 days 00:00:00.030474,0.200529,NaN,SVM,scale,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
98,98,0.789572,2026-03-22 20:23:49.057958,2026-03-22 20:23:49.087956,0 days 00:00:00.029998,0.152296,NaN,SVM,scale,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
99,99,0.785847,2026-03-22 20:23:49.089960,2026-03-22 20:23:49.126968,0 days 00:00:00.037008,0.286177,NaN,SVM,scale,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE

In [27]:
study.trials_dataframe()['params_classifier'].value_counts()

params_classifier
SVM                 79
RandomForest        11
GradientBoosting    10
Name: count, dtype: int64

In [28]:
study.trials_dataframe()['params_classifier'].value_counts()

params_classifier
SVM                 79
RandomForest        11
GradientBoosting    10
Name: count, dtype: int64

In [30]:
# 1. Optimization History
plot_optimization_history(study).show()

In [31]:
# 3. Slice Plot
plot_slice(study).show()

In [32]:
# 5. Hyperparameter Importance
plot_param_importances(study).show()

In [ ]:
import optuna
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score
import numpy as np

# Load the Iris dataset
X, y = load_iris(return_X_y=True)

# Split the dataset into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Define the objective function for XGBoost
def objective(trial):
    # Hyperparameter search space
    param = {
        'verbosity': 0,
        'objective': 'multi:softprob',
        'num_class': 3,
        'eval_metric': 'mlogloss',  # Ensure that the eval_metric is specified here
        'booster': 'gbtree',
        'lambda': trial.suggest_float('lambda', 1e-8, 1.0, log=True),
        'alpha': trial.suggest_float('alpha', 1e-8, 1.0, log=True),
        'eta': trial.suggest_float('eta', 0.01, 0.3),
        'gamma': trial.suggest_float('gamma', 1e-8, 1.0, log=True),
        'max_depth': trial.suggest_int('max_depth', 3, 9),
        'min_child_weight': trial.suggest_int('min_child_weight', 1, 10),
        'subsample': trial.suggest_float('subsample', 0.4, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.4, 1.0),
        'n_estimators': 300,
    }

    # Create DMatrix for XGBoost
    dtrain = xgb.DMatrix(X_train, label=y_train)
    dtest = xgb.DMatrix(X_test, label=y_test)

    # Define a pruning callback based on evaluation metrics
    pruning_callback = optuna.integration.XGBoostPruningCallback(trial, "eval-mlogloss")  # Match the metric name in the evals list

    # Train the model
    bst = xgb.train(
        param,
        dtrain,
        num_boost_round=300,
        evals=[(dtrain, "train"), (dtest, "eval")],  # Ensure the eval datasets and names are specified
        early_stopping_rounds=30,
        callbacks=[pruning_callback]
    )

    # Predict on the test set
    preds = bst.predict(dtest)
    best_preds = [int(np.argmax(line)) for line in preds]

    # Return accuracy as the objective value
    accuracy = accuracy_score(y_test, best_preds)
    return accuracy

# Create a study with pruning
study = optuna.create_study(direction='maximize', pruner=optuna.pruners.SuccessiveHalvingPruner())
study.optimize(objective, n_trials=50)

# Output the best trial
print(f"Best trial: {study.best_trial.params}")
print(f"Best accuracy: {study.best_value}")

In [ ]:
from optuna.visualization import plot_intermediate_values

# 1. Plot intermediate values during the trials
plot_intermediate_values(study).show()